# This file is maintained by Tedium - manual edits will be overwritten!

version: "2.1"
jobs:
  cachekey:
    docker:
      - image: cimg/base:2026.06@sha256:deb111cac98e50249a996a413313b8e3d381f4ae2e7059b7e27dce02f61d744c
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task cachekey
      - persist_to_workspace:
          root: .
          paths:
            - ./.task-meta-cachekey*
  checkout:
    docker:
      - image: cimg/base:2026.06@sha256:deb111cac98e50249a996a413313b8e3d381f4ae2e7059b7e27dce02f61d744c
    steps:
      - checkout:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - .
  ci-all:
    docker:
      - image: cimg/base:2026.06@sha256:deb111cac98e50249a996a413313b8e3d381f4ae2e7059b7e27dce02f61d744c
    steps:
      - run:
          command: echo "Done"
  deps-go:
    docker:
      - image: docker.io/golang:1.26.3@sha256:2d6c80227255c3112a4d08e67ba98e58efd3846daf15d9d7d4c389565d881b1a
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
            - deps-go-v7-
      - run:
          command: |-
            export GOPATH=/.go
            export GOCACHE=/.gocache
            ./task deps-go
      - save_cache:
          key: deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
          paths:
            - /.go
            - /.gocache
  fetch-task:
    docker:
      - image: ghcr.io/markormesher/task-fetcher:v0.6.14@sha256:8765e5e5da8498074a2b7d2e2a083c6e7ce7859659053178178e04c32299997d
    steps:
      - attach_workspace:
          at: .
      - run:
          command: cp /task .
      - persist_to_workspace:
          root: .
          paths:
            - ./task
  imgbuild-imgpush:
    docker:
      - image: cimg/base:2026.06@sha256:deb111cac98e50249a996a413313b8e3d381f4ae2e7059b7e27dce02f61d744c
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |-
            echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
            ./task imgbuild
            ./task imgpush
  imgrefs:
    docker:
      - image: docker.io/alpine/git:v2.52.0@sha256:8786a6a02273827d0aa039d174aacd5e017fcce9aba0af62596d991970cab01a
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task imgrefs
      - persist_to_workspace:
          root: .
          paths:
            - ./.task-meta-imgrefs
            - ./**/.task-meta-imgrefs
  lint-go:
    docker:
      - image: docker.io/golang:1.26.3@sha256:2d6c80227255c3112a4d08e67ba98e58efd3846daf15d9d7d4c389565d881b1a
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
            - deps-go-v7-
      - run:
          command: |-
            export GOPATH=/.go
            export GOCACHE=/.gocache
            ./task lint-go
workflows:
  version: 2
  main:
    jobs:
      - checkout:
          requires: []
          filters:
            tags:
              only: /.*/
      - fetch-task:
          requires: []
          filters:
            tags:
              only: /.*/
      - imgrefs:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - cachekey:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - deps-go:
          requires:
            - cachekey
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - lint-go:
          requires:
            - checkout
            - deps-go
            - fetch-task
          filters:
            tags:
              only: /.*/
      - imgbuild-imgpush:
          requires:
            - checkout
            - fetch-task
            - imgrefs
            - lint-go
          filters:
            tags:
              only: /.*/
      - ci-all:
          requires:
            - deps-go
            - imgbuild-imgpush
            - imgrefs
            - lint-go
          filters:
            tags:
              only: /.*/
