# This file is maintained by Tedium - manual edits will be overwritten!

version: "2.1"
jobs:
  cachekey:
    docker:
      - image: cimg/base:2026.03@sha256:fdfacc6ce19a878cdacd7af20adf2b7a6dd0c0965b453c73844409bfbe882377
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task cachekey
      - persist_to_workspace:
          root: .
          paths:
            - ./.task-meta-cachekey*
  checkout:
    docker:
      - image: cimg/base:2026.03@sha256:fdfacc6ce19a878cdacd7af20adf2b7a6dd0c0965b453c73844409bfbe882377
    steps:
      - checkout:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - .
  ci-all:
    docker:
      - image: cimg/base:2026.03@sha256:fdfacc6ce19a878cdacd7af20adf2b7a6dd0c0965b453c73844409bfbe882377
    steps:
      - run:
          command: echo "Done"
  deps-go:
    docker:
      - image: docker.io/golang:1.26.1@sha256:c7e98cc0fd4dfb71ee7465fee6c9a5f079163307e4bf141b336bb9dae00159a5
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
            - deps-go-v7-
      - run:
          command: |-
            export GOPATH=/.go
            export GOCACHE=/.gocache
            ./task deps-go
      - save_cache:
          key: deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
          paths:
            - /.go
            - /.gocache
  fetch-task:
    docker:
      - image: ghcr.io/markormesher/task-fetcher:v0.6.3@sha256:554d10aeafc5d3f840df736ebba7b495f181579ce7c1fbf85562b90ec9e0bd75
    steps:
      - attach_workspace:
          at: .
      - run:
          command: cp /task .
      - persist_to_workspace:
          root: .
          paths:
            - ./task
  imgbuild-imgpush:
    docker:
      - image: cimg/base:2026.03@sha256:fdfacc6ce19a878cdacd7af20adf2b7a6dd0c0965b453c73844409bfbe882377
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |-
            echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
            ./task imgbuild
            ./task imgpush
  imgrefs:
    docker:
      - image: docker.io/alpine/git:v2.52.0@sha256:d453f54c83320412aa89c391b076930bd8569bc1012285e8c68ce2d4435826a3
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task imgrefs
      - persist_to_workspace:
          root: .
          paths:
            - ./.task-meta-imgrefs
            - ./**/.task-meta-imgrefs
  lint-go:
    docker:
      - image: docker.io/golang:1.26.1@sha256:c7e98cc0fd4dfb71ee7465fee6c9a5f079163307e4bf141b336bb9dae00159a5
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-go-v7-{{ checksum ".task-meta-cachekey-go" }}
            - deps-go-v7-
      - run:
          command: |-
            export GOPATH=/.go
            export GOCACHE=/.gocache
            ./task lint-go
workflows:
  version: 2
  main:
    jobs:
      - checkout:
          requires: []
          filters:
            tags:
              only: /.*/
      - fetch-task:
          requires: []
          filters:
            tags:
              only: /.*/
      - imgrefs:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - cachekey:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - deps-go:
          requires:
            - cachekey
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - lint-go:
          requires:
            - checkout
            - deps-go
            - fetch-task
          filters:
            tags:
              only: /.*/
      - imgbuild-imgpush:
          requires:
            - checkout
            - fetch-task
            - imgrefs
            - lint-go
          filters:
            tags:
              only: /.*/
      - ci-all:
          requires:
            - deps-go
            - imgbuild-imgpush
            - imgrefs
            - lint-go
          filters:
            tags:
              only: /.*/
