# This file is maintained by Tedium - manual edits will be overwritten!
name: CI
"on":
  - push
jobs:
  check-root-go:
    runs-on: ubuntu-latest
    container:
      image: docker.io/golang:1.27.1@sha256:3680233e3204827fbdc66088528ae6d4b3d034f51d03a99d454f6de034888244
    steps:
      - uses: markormesher/ci-resources/setup@62ded02daecfff84429580ffb8539b570ec5ba5e # v0.9.0
      - env:
          CI_CACHE_TOKEN: ${{ secrets.CI_CACHE_TOKEN }}
        run: ./task -s cacheload-root-go
      - run: ./task -s deps-root-go
      - run: ./task -s lint-root-go
      - env:
          CI_CACHE_TOKEN: ${{ secrets.CI_CACHE_TOKEN }}
        run: ./task -s cachesave-root-go
  ci-all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check-root-go
      - img-root
    container:
      image: docker.io/busybox:1.38.0@sha256:fd7dc98638c8e305f4dc34e979f1c0fdfdcaeb0fbf8fcff77ae834b6da3d7e6e
    steps:
      - run: |2
          results=$(echo '${{ toJson(needs) }}' | (grep '"result"' || echo))
          if echo "$results" | grep -q "failure\|cancelled\|skipped"; then
            echo "One or more jobs failed, were cancelled, or were skipped" >&2
            exit 1
          fi
          echo "All jobs passed"
  img-root:
    runs-on: ubuntu-latest
    needs:
      - check-root-go
    permissions:
      packages: write
    steps:
      - uses: markormesher/ci-resources/setup@62ded02daecfff84429580ffb8539b570ec5ba5e # v0.9.0
      - run: buildah login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
      - run: ./task -s imgrefs-root
      - run: ./task -s imgbuild-root
      - run: ./task -s imgpush-root
