# This file is maintained by Tedium - manual edits will be overwritten!
name: CI
"on":
  - push
jobs:
  check-root-go:
    runs-on: ubuntu-latest
    container:
      image: docker.io/golang:1.27.1@sha256:512690a5660563b57d37ecc31129e7f136e831db2aed24a1dbeb8ad7380dc0fa
    steps:
      - uses: markormesher/ci-resources/setup@62ded02daecfff84429580ffb8539b570ec5ba5e # v0.9.0
      - env:
          CI_CACHE_TOKEN: ${{ secrets.CI_CACHE_TOKEN }}
        run: ./task -s cacheload-root-go
      - run: ./task -s deps-root-go
      - run: ./task -s lint-root-go
      - env:
          CI_CACHE_TOKEN: ${{ secrets.CI_CACHE_TOKEN }}
        run: ./task -s cachesave-root-go
  ci-all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check-root-go
      - img-root
    container:
      image: docker.io/busybox:1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
    steps:
      - run: |2
          results=$(echo '${{ toJson(needs) }}' | (grep '"result"' || echo))
          if echo "$results" | grep -q "failure\|cancelled\|skipped"; then
            echo "One or more jobs failed, were cancelled, or were skipped" >&2
            exit 1
          fi
          echo "All jobs passed"
  img-root:
    runs-on: ubuntu-latest
    needs:
      - check-root-go
    permissions:
      packages: write
    steps:
      - uses: markormesher/ci-resources/setup@62ded02daecfff84429580ffb8539b570ec5ba5e # v0.9.0
      - run: buildah login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
      - run: ./task -s imgrefs-root
      - run: ./task -s imgbuild-root
      - run: ./task -s imgpush-root
